-- MySQL Script generated by MySQL Workbench
-- Wed Oct 27 20:02:38 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema semestralka_web
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `miravdov_pravo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `miravdov_pravo` ;

CREATE TABLE IF NOT EXISTS `miravdov_pravo` (
  `id_pravo` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(25) NOT NULL,
  `vaha` INT NOT NULL,
  PRIMARY KEY (`id_pravo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miravdov_uzivatel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `miravdov_uzivatel` ;

CREATE TABLE IF NOT EXISTS `miravdov_uzivatel` (
  `id_uzivatel` INT NOT NULL AUTO_INCREMENT,
  `id_pravo` INT NOT NULL,
  `jmeno` VARCHAR(60) NOT NULL,
  `login` VARCHAR(30) NOT NULL,
  `heslo` VARCHAR(60) NOT NULL,
  `email` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`id_uzivatel`),
  INDEX `fk_miravdov_uzivatel_miravdov_pravo_idx` (`id_pravo` ASC),
  CONSTRAINT `fk_uzivatel_pravo`
    FOREIGN KEY (`id_pravo`)
    REFERENCES `miravdov_pravo` (`id_pravo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miravdov_clanek`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `miravdov_clanek` ;

CREATE TABLE IF NOT EXISTS `miravdov_clanek` (
  `id_clanku` INT NOT NULL AUTO_INCREMENT,
  `obsah` LONGTEXT NOT NULL,
  `datum` DATETIME NOT NULL,
  `id_uzivatel` INT NOT NULL,
  `nadpis` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_clanku`),
  INDEX `fk_miravdov_clanek_miravdov_uzivatel1_idx` (`id_uzivatel` ASC),
  CONSTRAINT `fk_miravdov_clanek_miravdov_uzivatel1`
    FOREIGN KEY (`id_uzivatel`)
    REFERENCES `miravdov_uzivatel` (`id_uzivatel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miravdov_recenze`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `miravdov_recenze` ;

CREATE TABLE IF NOT EXISTS `miravdov_recenze` (
  `id_recenze` INT NOT NULL AUTO_INCREMENT,
  `datum` DATETIME NOT NULL,
  `obsah` LONGTEXT NOT NULL,
  `id_clanku` INT NOT NULL,
  `bodove_hodnoceni` DECIMAL NOT NULL,
  PRIMARY KEY (`id_recenze`),
  INDEX `fk_miravdov_recenze_miravdov_clanek1_idx` (`id_clanku` ASC),
  CONSTRAINT `fk_miravdov_recenze_miravdov_clanek1`
    FOREIGN KEY (`id_clanku`)
    REFERENCES `miravdov_clanek` (`id_clanku`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `miravdov_pravo`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `miravdov_pravo` (`id_pravo`, `nazev`, `vaha`) VALUES (1, 'SuperAdmin', 20);
INSERT INTO `miravdov_pravo` (`id_pravo`, `nazev`, `vaha`) VALUES (2, 'Admin', 10);
INSERT INTO `miravdov_pravo` (`id_pravo`, `nazev`, `vaha`) VALUES (3, 'Recenzenz', 5);
INSERT INTO `miravdov_pravo` (`id_pravo`, `nazev`, `vaha`) VALUES (4, 'Autor', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `miravdov_uzivatel`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `miravdov_uzivatel` (`id_uzivatel`, `id_pravo`, `jmeno`, `login`, `heslo`, `email`) VALUES (1, 1, 'Hlavní správce', 'admin', 'admin', 'pokus1@seznam.cz');
INSERT INTO `miravdov_uzivatel` (`id_uzivatel`, `id_pravo`, `jmeno`, `login`, `heslo`, `email`) VALUES (2, 3, 'Pokusný recenzant', 'recenzanz', 'recenzant', 'pokus2@seznam.cz');
INSERT INTO `miravdov_uzivatel` (`id_uzivatel`, `id_pravo`, `jmeno`, `login`, `heslo`, `email`) VALUES (3, 4, 'Pokusný autor', 'autor', 'autor', 'pokus3@seznam.cz');

COMMIT;

